name: Build Feedpushr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get -y install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make build test

    - name: Distribution
      run: make distribution
      if: startsWith(github.ref, 'refs/tags/')
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/feedpushr-linux-amd64.tgz
          release/feedpushr-linux-arm64.tgz
          release/feedpushr-linux-arm.tgz
          release/feedpushr-windows-amd64.tgz
          release/feedpushr-darwin-amd64.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
